### ISSUE TITLE
Cross compile from Linux to Windows fails due to glslang build problem.

### ISSUE THREAD

**Issue by John-Nagle** [BVE-Reborn/rend3#103]
Some minor problem with gslang's build system. Gslang issue filed:

https://github.com/KhronosGroup/glslang/issues/2572

Posted here mostly for reference. No action needed at this time.

**Comment by cwfitzgerald** [comment]
See also #104

**Comment by cwfitzgerald** [comment]
We should likely also have this in CI if this is a thing people do
