### ISSUE TITLE
Validate PBR Impl Against GLTF Sample Models

### ISSUE THREAD

**Issue by cwfitzgerald** [BVE-Reborn/rend3#135]
![](https://cwfitz.com/3gPsFD.png) is totally messed up. I should validate against the gltf test models found here.

**Comment by John-Nagle** [comment]
Here's that model from the test set, with Rend3 0.5.2. 

./rend3/target/release/scene-viewer MetalRoughSpheres/glTF-Embedded/MetalRoughSpheres.gltf

![roughnessmetallictest](https://user-images.githubusercontent.com/942608/139728395-07dff102-f300-4fcc-b004-cfce311e3d95.png)

Here's the reference image of what that's supposed to look like.

![screenshot](https://user-images.githubusercontent.com/942608/139728495-db12971f-9f27-4589-9381-c42ec2385e0e.png)

So it looks like the roughness and metallic data makes it to the shaders, but doesn't do what it should. Roughness barely does anything, which is what I see in my own code.

**Comment by John-Nagle** [comment]
Tried the same test models as last time. Now, no texturing at all.

![rend3-notexturesvisible](https://user-images.githubusercontent.com/942608/147859569-1f3593b5-6166-4b8b-bc6c-a8c922ad06b6.png)

**Comment by John-Nagle** [comment]
Also tried .gltf instead of .glb

./scene-viewer  ../../../rend3-tests/MetalRoughSpheres/glTF/MetalRoughSpheres.gltf

Same result.

No errors are reported by the program. It's as if all the textures are being totally ignored. No sign of lighting or shadows, either.

Also, when the rendered window gets focus, the cursor disappears. The rendered window will not give up focus until a new window is opened, which will restore the cursor. Linux 20.04 LTS.

**Comment by cwfitzgerald** [comment]
So that's because there is no directional light in the scene, so this is completely falling on ambient lighting preventing the colors from getting too dark. You can add a directional light by adding `--directional-light -1,-1,-1` to the command line.

As for the cursor grab, does escape let the grab go?

**Comment by John-Nagle** [comment]
Much better. New snapshot. Thanks. 

![rend3-texturesvisiblenew](https://user-images.githubusercontent.com/942608/147863224-b6970151-7c51-4eb9-8bb2-00a1397d4123.png)

**Comment by John-Nagle** [comment]
Yes, escape will bring the cursor back. Clicking outside the window will not. That's not wrong, it's something a real application has to handle.  

It's interesting that max smooth, above, looks much like max rough. All shinyness disappears. The reference image doesn't do that.

**Comment by cwfitzgerald** [comment]
What's exactly the failure mode of the selection? You click on the window and the cursor is grabbed, how do you cause the cursor to leave the window during the grab? (this should likely be its own issue)

**Comment by cwfitzgerald** [comment]
> It's interesting that max smooth, above, looks much like max rough. All shinyness disappears. The reference image doesn't do that.

The difference here is the reference image is using cubemap reflections, which work fine with a perfect mirror (i.e. roughness = 0). Here i"m using a directional light which has no area, so completely disappears under a perfect mirror. Not pretty, but expected.

**Comment by John-Nagle** [comment]
Oh, leaving the default ambient as the only illumination. Hence the dull white.
