### ISSUE TITLE
Iced Example

### ISSUE THREAD

**Issue by cwfitzgerald** [BVE-Reborn/rend3#14]
We need some solution to 2D rendering for doing UIs such as imgui. We have a couple of options:
 - Integrate with imgui directly, taking a ready-to-render frame, and rendering it.
 - Provide a 2D rendering interface that we could implement an imgui renderer on top of.
 - Don't support it at all, letting external integration deal with it. This means a user could have rend3 render to the swapchain, then they would render the UI on top of it later (see https://github.com/BVE-Reborn/rend3/issues/15)

Todo:
- [x] Support external resources (#40 and #41)
- [x] Imgui example (#42)
- [ ] Iced example

**Comment by snordgren** [comment]
Iced works well with WGPU rendering and is easy to setup. There is a good example [here](https://github.com/hecrj/iced/tree/master/examples/integration) showing how to set up WGPU rendering with Iced on top. It's also a good model for #15. Maybe there could be an example showing how to use Iced, or an external Imgui WGPU renderer, but implementing an Imgui backend seems like it would be a bit out of scope.

**Comment by cwfitzgerald** [comment]
Yeah I agree. I think I've settled on the 3rd method as the way to do things. Thank you for that link to the iced integration model, I'll take a look and see if there's anything I can glean from it.

**Comment by cwfitzgerald** [comment]
Closing in favor of #192 as it has more up to date information.
