### ISSUE TITLE
Request more informative message on panic

### ISSUE THREAD

**Issue by John-Nagle** [BVE-Reborn/rend3#153]
I'm intermittently getting this crash. This is probably due to passing a previously deleted handle into Rend3 and is probably a problem in my code. The trouble is, this error occurs long after the bad call. The API just puts requests on the queue, and they are processed later during the draw cycle. **So I can't tell which call caused the trouble.**

The code at registry.rs:52 is 

self.mapping.get_index_of(&handle).unwrap()

and the "unwrap" is failing.

Something that panics with a message that includes the value of "handle" would be helpful. Thanks.

Non-useful backtrace: 

thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /home/john/.cargo/registry/src/github.com-1ecc6299db9ec823/rend3-0.0.5/src/registry.rs:52:44
stack backtrace:
   0: rust_begin_unwind
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:50:5
   3: wgpu_conveyor::AutomatedBuffer::write_to_buffer
   4: rend3::renderer::material::MaterialManager::ready
   5: rend3::renderer::render::render_loop::{{closure}}
   6: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   8: switchyard::task::ThreadLocalTask<TD>::poll
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'main' panicked at 'Job panicked!', /home/john/.cargo/registry/src/github.com-1ecc6299db9ec823/switchyard-0.1.1/src/lib.rs:153:78

**Comment by cwfitzgerald** [comment]
Ah yeah, I see how that's a problem. I'll look into if I can do better then just the index.

In general better add/delete validation (or an improved more raii implementation) is definitely needed. If all handles were Arc-like, would this name resource management easier or harder for you?

**Comment by John-Nagle** [comment]
What I thought was the problem, wasn't. Still a bad handle, but haven't found the problem in my code yet. This is hard to debug, because you can put a dead handle in the instruction queue, and you don't find out until the next frame cycle that it's bad. So, would definitely recommend the Arc approach. Manually releasing assets is so C.
