### ISSUE TITLE
Cross-compile to Windows will compile, but fails under Wine.

### ISSUE THREAD

**Issue by John-Nagle** [BVE-Reborn/rend3#157]
New "scene-viewer" compiles and runs fine on Linux 20.04 LTS.

Tried cross-compiling to Windows. Compiles OK for "x86_64-pc-windows-gnu" target. Some additional DLLs from the MinGW libraries have to be copied to the directory containing the Windows executable.  It gets far enough to open the graphics window, but aborts trying to initialize the Vulkan level. 

This Wine patch, about three weeks old, might be relevant. Apparently other programs have hit this problem: https://source.winehq.org/patches/data/210588
The memory type requested is not compatible with what Wine is offering, apparently.

Error message:

Cross-compiled "scene-viewer":
`cargo build --target=x86_64-pc-windows-gnu`

 ```
wine ./scene-viewer.exe
fixme:d3d12_device_CheckFeatureSupport: Assuming device does not support tile based rendering.
fixme:d3d12_device_CheckFeatureSupport: Assuming NUMA.
fixme:d3d12_device_CheckFeatureSupport: Unhandled feature 0x12.
fixme:vkd3d_select_memory_type: Custom heaps not supported yet.
fixme:vkd3d_select_memory_type: Custom heaps not supported yet.
fixme:vkd3d_allocate_device_memory: Failed to find suitable memory type (allowed types 0x82).
[ERROR wgpu_hal::dx12] Texture creation failed: 0x80004005
[ERROR wgpu::backend::direct] wgpu error: Validation Error
    
    Caused by:
        In Device::create_texture
          note: label = `null D2 texture`
        parent device is lost

**Comment by cwfitzgerald** [comment]
This seems to be an issue with vkd3d being incomplete. We might be able to tune wgpu-hal to select reasonable memory types here.

**Comment by cwfitzgerald** [comment]
Might be worthwhile to file an issue with wgpu. If you try the cube example of wgpu, seems like you might hit the same issue. That patch does look like it would help.

**Comment by John-Nagle** [comment]
WGPU's "cube.exe" fails in the same way. So it's not Rend3 causing the crash.

**Comment by John-Nagle** [comment]
Filed an issue for WGPU: https://github.com/gfx-rs/wgpu/issues/1854
It's down one more level. Close here, please.

**Comment by cwfitzgerald** [comment]
Thanks!
