### ISSUE TITLE
Memory leak in scene-viewer demo

### ISSUE THREAD

**Issue by happydpc** [BVE-Reborn/rend3#167]
When running the demo, the memory usage increases continually.

**Comment by cwfitzgerald** [comment]
This is on the latest commit? What backend/hardware are you using?

I'll investigate in a bit.

**Comment by happydpc** [comment]
Yes, with the latest commit in windows 10 vulkan with RTX2070.

**Comment by cwfitzgerald** [comment]
Unfortunately I can't seem to replicate it on Windows/VK/1080ti. In what way were you measuring the amount of memory used?

**Comment by happydpc** [comment]
In the task monitor, after about 5 minutes, it increases from 240MB to 500MB. After 10 minutes, it is 665MB now.

![image](https://user-images.githubusercontent.com/771776/131439404-8cf45f1c-18c1-48c5-87f3-6e8843103e91.png)

**Comment by cwfitzgerald** [comment]
Alright, I can reproduce this, and likely know what the culprit is, wgpu's allocator growing tracking structures but never shrinking them. Following up with an issue on the allocator.

**Comment by cwfitzgerald** [comment]
Alright, with the linked issue fixed, the leaks go away in release. There is still a leak in debug, which I suspect is related to the vulkan validation layers. Will investigate that separately.
