### ISSUE TITLE
Make Renderer Calls Immedate

### ISSUE THREAD

**Issue by cwfitzgerald** [BVE-Reborn/rend3#177]
All non-render function calls currently push an event on a queue to be processed at render time. This causes issues when there is a lot of texture processing to do. These should be made immediate, with lock usage optimized to allow concurrent access.

cc @John-Nagle

**Comment by John-Nagle** [comment]
This should help with texture loading causing brief stalls of the render thread.

I'm not sure about giving up the instruction list entirely, though. Some groups of changes need to be performed as an atomic operation. For example, when something is moving, the transforms of all its objects transforms need to be updated on the same frame, to prevent tearing effects.

**Comment by cwfitzgerald** [comment]
So you bring up an interesting point: it would still be atomic, but it would be atomic because there would be a massive hang on the user threads as the locks would be taken. I think the solution here is a hybrid one. Handle allocation and all wgpu uploading work is conducted immediately, then the very last step of adding it to the registry gets deferred until render. This would keep event processing very quick, offload the work we want to other threads, and keep atomicity without hangs.
