### ISSUE TITLE
Consider math-agnostic API

### ISSUE THREAD

**Issue by kvark** [BVE-Reborn/rend3#178]
Looks like the API is hand-wired to use `glam` currently. Are there any barriers to expose [mint](https://github.com/kvark/mint) instead, thus turning `glam` to be a private dependency?

**Comment by cwfitzgerald** [comment]
I don't really have a good reason for not exposing mint at the edge besides convenience and not needing to spam `.into()` all over the place. There is an interesting question that falls out of this which is how much should be mint vs glam -- I expose a lot of my private apis as public to allow people to implement their own render routines. It would be a bother to expose _all_ of that as mint. I think a reasonable middle ground would be having the "user" facing api be mint and the "implementer" api be glam.

This would still mean upgrading glam is a semver break, but this whole crate is basically a semver trap as it is.

**Comment by kvark** [comment]
I see. Yeah, exposing all the internals doesn't work very well with `mint`. Feel free to close!

**Comment by cwfitzgerald** [comment]
Not going to close this as I'm not sure what I want to end up doing, but going to pull this off v0.1.0
