### ISSUE TITLE
RendererBuilder::new shouldn't accept InternalSurfaceOptions

### ISSUE THREAD

**Issue by kvark** [BVE-Reborn/rend3#179]
It would be cleaner if it accepted `RendererConfiguration`, or alternatively had no arguments and allowed doing something like:
```rust
rend3::RendererBuilder::new()
        .window(&window)
        .surface_size(UVec2::new(window_size.width, window_size.height)) // shouldn't be needed?
        .vsync(rend3::VSyncMode::On)
        .build(),
```

**Comment by cwfitzgerald** [comment]
We need the surface size for initial surface configure. There's the deeper question if rend3 should be dealing with internal surfaces at all, but I think the user convenience is worth it. There's also rather annoying combinatorics involved as rend3 can both use an existing instance/adapter/device and a self-created. The combinations are:

1. Internal IAD, Internal Surface:  I need a window + size.
2. Internal IAD, External Surface:  I need a surface.
3. Internal IAD, Render-to-Texture: I need nothing.
4. External IAD, Internal Surface:  I need a window + size.
5. External IAD, External Surface:  I need nothing. (Compat is on the user)
6. External IAD, Render-to-Texture: I need nothing.

Splitting this up sanely is going to be fun :)

**Comment by cwfitzgerald** [comment]
Oh, I've got it. I should make all IADs external. Then I provide a convenience function that can generate the IAD with a single function call. This is just as easy on the user, and makes the combinatorics much simpler.

By that same rule, why not just make all surfaces external too, it's like 4 more lines of code on the user, and prevents rend3 needing glorified passthrough of reconfigures 🤔.
