### ISSUE TITLE
Transparency mode problems

### ISSUE THREAD

**Issue by John-Nagle** [BVE-Reborn/rend3#189]
Transparency mode has some unexpected behavior.

- Opaque - works as expected. Casts shadows.
- Cutout - alpha channel works, but objects do not cast shadows.
- Blend - frantic flickering from frame to frame as different faces appear on top.

Attached are three screenshots of the same scene, just sitting on screen with no changes being made. It looks like depth sorting is producing random sort order. This is with everything in "Blend" mode, which is just for test purposes.

Notes:

Cutout mode should cast shadows. Sunlight through the windowpanes is common.

A non-sorting form of blend would be useful. Second Life data has too much stuff set to "blend" that really doesn't need it. Remember that paper from NVidia on Weighted, Blended Order-Independent Transparency? Something like that.

![all-blend-mode-1](https://user-images.githubusercontent.com/942608/133136575-aa1edbe2-ffa0-4c2f-9e50-cbee53eda94f.png)
![all-blend-mode-2](https://user-images.githubusercontent.com/942608/133136577-107c633a-0c78-4119-9372-791f50f8aebc.png)
![all-blend-mode-3](https://user-images.githubusercontent.com/942608/133136578-a6dab020-1fa9-485b-a0dc-9cc9c2f74d9f.png)

**Comment by John-Nagle** [comment]
On a related note, what happens with RGB (no alpha) textures? It would be helpful if providing an RGB-only texture forced "Opaque" mode, because it's possible for something to initiate a texture swap without changing the material settings.

**Comment by cwfitzgerald** [comment]
> Cutout mode should cast shadows. Sunlight through the windowpanes is common.

I suspect this might be a different issue. When I render shadows, I do _front_ face culling, as it prevents some nasty artifacting on the front surface of solid objects. If the objects are not solid though, they get completely culled away. Do you think this might be the underlying cause?

> Attached are three screenshots of the same scene, just sitting on screen with no changes being made. It looks like depth sorting is producing random sort order. This is with everything in "Blend" mode, which is just for test purposes.

I have actually seen something that looks suspiciously like this on one of my other scenes. Just for debugging purposes, do you have the latest version of wgpu-hal (0.10.6), there was a bug that was fixed in... 0.10.4 which caused some crazy culling results on nvidia.

> On a related note, what happens with RGB (no alpha) textures?

This is a weird case, as you can have alpha without having alpha in your texture. Set material color mode to TextureValue and have a value with an alpha, for example (some goes with any of the other vert modes). So I'm not sure there's a way to do this that doesn't violate the principle of least surprise.

**Comment by John-Nagle** [comment]
I have, from Cargo.lock

    wgpu 0.10.1
    wgpu-core 0.10.2
    wgpu-hal 0.10.4

I don't specify the versions on any of those; those are all dependencies of something else.

I took the version numbers used in scene-tester's "Cargo.toml" file for my own:

    rend3 = "^0.1.0"
    rend3-gltf = "^0.1.0"
    rend3-pbr = "^0.1.0"

**Comment by cwfitzgerald** [comment]
Alright, that _should_ have the bug fixed in it already. You can do `cargo update -p wgpu -p wgpu-core -p wgpu-hal` to update those particular packages, though it likely won't help.

I will investigate this soon

**Comment by John-Nagle** [comment]
OK, thanks. Meanwhile I changed Cargo.toml to use Rend3 0.1.1, did "cargo update", tried "Blend mode" again, and got the frantic flickering again. 

(I still like the idea of Weighted, Blended Order-Independent Transparency. Most of the translucency I have to deal with is slightly tinted windows, a lot of them, through which you can see lots of stuff, often distant stuff, that would have to be sorted. So eliminating the sort does have its appeal.)

**Comment by John-Nagle** [comment]
Forward progress. The big Babbage Palisade scene is rendering reasonably, except for shadows.

I'm avoiding "Blend" mode for now, and just using "Opaque" and "Cutout" modes. "Opaque" objects cast shadows, and "Cutout" ones seem to do so intermittently, with frantic flickering. The three screenshots below are of the same scene, just being refreshed without changes. Shadows are quite different.

![shadowtest1](https://user-images.githubusercontent.com/942608/133201233-a6b541a2-9c65-4ca2-bb3d-830d330c094e.png)
![shadowtest2](https://user-images.githubusercontent.com/942608/133201275-1de51ef7-5863-4dbc-b068-0cbd3a141195.png)
![shadowtest3](https://user-images.githubusercontent.com/942608/133201285-3e0c67e2-da78-464d-9f3e-7eb1bcfce996.png)

There's also momentary flickering when my code does an update_material to replace a texture. The flickering is slower in debug builds, and very noticeable. 

Question: I submit a MaterialChange structure with all fields filled in, no None entries, even if only some fields are changing, Does that add overhead?

Minor note: with "Debug" level logging on, loading that scene generates 1.2GB of log and runs at 2 FPS. Even "Info" level logging has too much detail. Suggest moving some of the more verbose logging to lower log levels.

**Comment by cwfitzgerald** [comment]
> Question: I submit a MaterialChange structure with all fields filled in, no None entries, even if only some fields are changing, Does that add overhead?

Shouldn't. Materials are small and the update code is (macro generated) straight-line `if let Some(new) = change.field { mat.field = new }` kinda deal.

> Minor note: with "Debug" level logging on, loading that scene generates 1.2GB of log and runs at 2 FPS. Even "Info" level logging has too much detail. Suggest moving some of the more verbose logging to lower log levels.

Alright, these all seem to be coming from wgpu in one form or another. I agree that we should probably move info -> debug and debug -> trace. Will follow up with an issue on wgpu. In the mean time, most loggers support filtering by module, so you can do `RUST_LOG=debug,wgpu_core=warn,naga=warn` or alternatively `RUST_LOG=warn,your_crate=debug`.

I suspect the shadow issue has to do with my culling not preserving the mapping of object -> info correctly. Will investigate once I have a minute. I have a repro of it, so I should be able to figure it out.

**Comment by cwfitzgerald** [comment]
There's something wrong with my GPU culling. If you turn CPU mode on (3rd argument to create_iad), shadows look right, and I bet transparency will too.

**Comment by cwfitzgerald** [comment]
Alright, it turns out the fix was erroneously never published. Try updating to make sure you have wgpu-core 0.10.3. There's still something funky going on with the shadows, but the non-deterministic behavior of transparency seems to have went away.
