### ISSUE TITLE
ExtendedAdapterInfo not exported

### ISSUE THREAD

**Issue by Noxime** [BVE-Reborn/rend3#190]
On current 0.1.0 `rend3::renderer::info::ExtendedAdapterInfo` is required to construct an `InstanceAdapterDevice`, but renderer module is private and the EAI is not re-exported publicly. Apparently ambient lights have the same issue

sorry for lazy issue im lazy

**Comment by cwfitzgerald** [comment]
Published in rend3 0.1.1
