### ISSUE TITLE
Add some form of immediate mode GUI integration

### ISSUE THREAD

**Issue by MindSwipe** [BVE-Reborn/rend3#192]
Some form of immediate mode GUI integration would be great, looking at the immediate mode GUI crates out there, I'm guessing [egui](https://github.com/emilk/egui) would be the easiest to integrate. And by "integrate" I mean expose a function that accepts a vector of [`ClippedMesh`](https://docs.rs/egui/0.14.2/egui/struct.ClippedMesh.html) and renders that to the screen.

I don't think handling [`Output`](https://docs.rs/egui/0.14.2/egui/struct.Output.html) has to be done by rend3, as it's here for copy/ pasting text, opening urls, setting the cursor icon and such, all stuff that happen outside the render engine

**Comment by cwfitzgerald** [comment]
We actually had an imgui example, but it didn't fit well with the new renderlist style. I definitely think this would be reasonable and in scope.

I am looking into how we could reasonably compose render lists. I don't know exactly what this is going to look like, but I'd love to be able to "chain" renderlists and support special input to renderlists such as a ClippedMesh and such.

It might be useful to talk about this synchronously. If you are on the [rust gamdev discord](https://discord.gg/yNtPTb2) we could chat there (I'm cwfitzgerald on there), or on the [wgpu-random matrix](https://matrix.to/#/#wgpu-random:matrix.org), or if not we can talk here.

**Comment by cwfitzgerald** [comment]
We should have both imgui and egui integrations. This likely would manifest as a crate which uses the appropriate wgpu integration.

- [ ] imgui integration
- [ ] egui integration

**Comment by resonant-jovian** [comment]
Hey, I am currently making a game using egui, the plan is to use rend3 for the 3D graphics. Happy to hear this is in the plan!
/Albin

**Comment by cwfitzgerald** [comment]
Great! I'm aiming to have this implemented in the next couple days, for the v0.2.0 milestone, so feedback on the apis is definitely appreciated.

**Comment by cwfitzgerald** [comment]
@AlbinSjoegren just fyi, this will likely slip to 0.3.0 as I don't want to block 0.2 on it, but the composable render list problem is next in line.

**Comment by MindSwipe** [comment]
To add to this with some information I gleaned from your talk last saturday, it may be worth it integrating existing WGPU rendering libraries instead of creating wholly new WGPU rendering code. Egui has a community maintained WGPU backend [here](https://github.com/hasenbanck/egui_wgpu_backend).

This would lessen then burden of maintaining these implementations

**Comment by cwfitzgerald** [comment]
That was definitely the plan! the rend3 side code would mainly be natively integrating the existing implementation into the render routine system. That way you really could just drop it in.

**Comment by MindSwipe** [comment]
That's great to hear, as I did a test-integration on my fork over [here](https://github.com/MindSwipe/rend3/tree/egui-integration), alongside an example of how to use it [here](https://github.com/MindSwipe/rend3/tree/egui-integration/examples), it'd be great if you could give it a look-over and say if there's anything major missing/ wrong. I'd especially like your input on two things

1. What to do when the implemented RenderRoutine can fail, see [this](https://github.com/MindSwipe/rend3/blob/egui-integration/rend3-egui/src/lib.rs#L69) specific piece of code. Currently I'm just calling `unwrap` which means the entire application will panic if rendering egui failed, and I don't think that's a particularly good idea, but I may be wrong.
2. It feels kinda wrong not using `ManagerReadyOutput`, but that may just be my inexperience with rend3
