### ISSUE TITLE
Expose `load_meshes` and `load_materials_and_textures` from rend3_gltf

### ISSUE THREAD

**Issue by cwfitzgerald** [BVE-Reborn/rend3#197]
> I think how rend3_gltf is made to render a scene is fine, but maybe it could offer something for the gltf-as-a-library approach (when the gltf file contains named meshes with no scene or nodes), and the ECS stuff or exactly how a dynamic scene is structured is out of scope I think.

_Originally posted by @jamen in https://github.com/BVE-Reborn/rend3/discussions/196#discussioncomment-1345438_

**Comment by jamen** [comment]
I'll experiment more in a local copy, see if I can render gltf with the help of hecs and rend3-pbr. I might need to expose other functions. It might make sense to do a different structure too (maybe the hashmap can be string -> mesh, there's no more nodes, and its no longer a scene)
