### ISSUE TITLE
CameraProjection nomeclature

### ISSUE THREAD

**Issue by dasifefe** [BVE-Reborn/rend3#231]
The `CameraProjection` enumerator has `Orthographic` and `Projection` modes:

```Rust
pub enum CameraProjection {
    Orthographic {
        size: Vec3A,
    },
    Projection { // Should be "Perspective".
        vfov: f32,
        near: f32,
    },
}
```

I believe that the enumerator mode `Projection` should be `Perspective`, no?

**Comment by cwfitzgerald** [comment]
Ah, yes it should be, nice catch! If you're up to fixing it, PR's welcome, otherwise I'll fix it tonight.

**Comment by dasifefe** [comment]
I will send the PR.
