### ISSUE TITLE
Texture Format Is Not Validated Against Usage

### ISSUE THREAD

**Issue by John-Nagle** [BVE-Reborn/rend3#251]
I'm trying to set up the AOMR value for a material. The goal is to assemble an AOMR texture from 3 single-channel textures:

`AoMRTextures::BWSplit{ao_texture: None, m_texture: None, r_texture: handle.texture_handle_aux.clone()})
`
So, here I'm building the r_texture:

```
let roughness_texture = Texture {
        label: Some(format!("{:?}", uuid_key_range)),
        format: TextureFormat::R8Uint,   // ???
        size: UVec2::new(roughness.width(), roughness.height()),
        data: roughness.into_raw(),
        //// TODO: automatic mipmapping (#53)
        mip_count: rend3::types::MipmapCount::Specific(NonZeroU32::new(mips).unwrap()),
        mip_source: rend3::types::MipmapSource::Uploaded,
    };
    let roughness_texture_handle =
        base.renderer_link.add_texture_2d(roughness_texture); 
```

Crash at add_texture_2D:

```
03:58:10 [WARN] Unrecognized device error ERROR_VALIDATION_FAILED_EXT
Memory block wasn't deallocated
03:58:10 [ERROR] Handling wgpu errors as fatal by default
thread 'Updater' panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_texture
    parent device is lost

', /home/john/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.11.0/src/backend/direct.rs:2195:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:517:5
   1: std::panicking::begin_panic_fmt
             at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:460:5
   2: wgpu::backend::direct::default_error_handler
   3: core::ops::function::Fn::call
   4: <wgpu::backend::direct::Context as wgpu::Context>::device_create_texture
   5: <wgpu::Device as wgpu::util::device::DeviceExt>::create_texture_with_data
   6: rend3::renderer::Renderer::add_texture_2d
   7: slscenetester::render::rendertextureconvert::convert_texture
   8: slscenetester::render::renderbase::RenderBase::apply_asset_reply
   9: slscenetester::jsonobjreader::WorldObjects::loadjsonobjects
```

Previously, I had `"ormat: TextureFormat::R8Unorm`. No crash, but the roughness channel didn't seem to do anything. After looking at the WGPU docs, it seemed that `R8Uint` (Red channel only, unsigned, 8 bits per channel) was the right choice there So I set that. 

Crash.

Am I putting the AOMR value together wrong, or what?

**Comment by cwfitzgerald** [comment]
R8Unorm is the correct format here. Inside a PBRMaterial I expect all textures to read as floating point, so if your actual texture is an 8 bit integer, for example, you need to use one of the two normalized formats so I can read it correctly.

That being said I need validation of this so you don't get this nasty crash and have a nice error message.

Roughness not working is probably #135
