### ISSUE TITLE
Bad behavior when adding objects to renderer inside event loop 

### ISSUE THREAD

**Issue by TheNoswad** [BVE-Reborn/rend3#256]
Using rend3 v0.2.2.
When an object is added to the renderer inside the event loop, all other objects 'inherit' the mesh and material of the newly added object. This only affects objects that were added inside of the event loop.

Objects that are added before the event loop are unaffected.

To reproduce this issue, add objects to the renderer inside the event loop.

Here is a screen recording of the issue. Hopefully, this helps.

https://user-images.githubusercontent.com/64293615/140786504-efcc6086-3b7e-45fb-8628-cced194b0b5c.mov

**Comment by cwfitzgerald** [comment]
Fixed in v0.2.3
