### ISSUE TITLE
Textures occasionally flash white during texture switching

### ISSUE THREAD

**Issue by John-Nagle** [BVE-Reborn/rend3#257]
See 

https://vimeo.com/user28693218

at 00:17 (the post)
at 00:24 (picture on wall above wine rack)
at 01:02 (sign on fence)
at 01:36 (vertical pipe on left side of steam engine)

This may be an NVidia driver bug, because it's been reported in other programs.

See:

- https://www.nvidia.com/en-us/geforce/forums/geforce-graphics-cards/5/227707/antialiasing-issuetexture-flickeringtexture-pop-in/
- https://community.secondlife.com/forums/topic/478264-viewer-performance-improvements/

It might be useful to take the textured cube example and have it switch between multiple copies of the same texture at a high rate to see if this can be replicated with a simple test case.

**Comment by cwfitzgerald** [comment]
Interesting, last time I did that with the cube example I didn't see anything on my nvidia card, but I'll recheck.

**Comment by cwfitzgerald** [comment]
Going to close, please re-open if it's still an issue.
