### ISSUE TITLE
Skeletal Animation

### ISSUE THREAD

**Issue by cwfitzgerald** [BVE-Reborn/rend3#27]
The current plan for dealing with this is to have:
 - Per-vert bone weights
 - Consume bone matrices then apply them internally on the cpu.
 - Transform the vertices on the gpu in a compute shader.

**Comment by snordgren** [comment]
The glTF sample viewer simply puts the bone matrices in uniforms and multiplies the weights by the matrices in the shader (see https://github.com/KhronosGroup/glTF-Sample-Viewer/blob/master/src/shaders/animation.glsl). Why use a compute shader instead of transforming vertices in the vertex shader?

**Comment by cwfitzgerald** [comment]
Thank you for your interest! :)

The main motivation for using a compute shader is that in a full rendering pipeline you might render a mesh, 4-8 times, maybe more:

- Up to 4 times per directional light (due to cascaded shadow mapping)
- Once per shadow casting non-directional light
- Possibly once for a z-prepass
- Once for the main opaque pass.

Numerous games (DOOM Eternal notably) have adopted the practice of pre-multiplying their skinning matrices to simplify the vert shaders of the following passes.

**Comment by snordgren** [comment]
Thank you for the response! That's a very sensible explanation, I found [this article](https://wickedengine.net/2017/09/09/skinning-in-compute-shader/) which notes some more advantages to skinning in the compute shader. Definitely seems like a worthwhile optimization. I don't know enough about rendering to be able to contribute but I'll be watching this project with great interest.

**Comment by cwfitzgerald** [comment]
Awesome! If you're interested in chatting a bit more casually, I have a discord server for my main project that'd I'd love to chat on: https://discord.gg/RxJHE2D
