### ISSUE TITLE
Refactor rend3-routines to be Less Crap

### ISSUE THREAD

**Issue by cwfitzgerald** [BVE-Reborn/rend3#280]
Right now every renderpass has its own ShaderInterfaces and this isn't very cash money of us.

**Comment by setzer22** [comment]
Something that would be very helpful and perhaps fits in this refactor is separating PBR from tonemapping.

Tonemapping should happen right at the end of the render pipeline, and right now adding any post-processing effects is not possible. There should be a way to get the HDR output from the PBR pipeline, run some filters on top of it, and finally (optionally?) feed it into the tonemapping routine.

What do you think?
