### ISSUE TITLE
Re-export `glam`

### ISSUE THREAD

**Issue by setzer22** [BVE-Reborn/rend3#282]
Currently `rend3` depends on `glam` 0.20, it would be a good idea to re-export that in case someone depends on two different crates which in turn depend on incompatible versions of `glam` (e.g. `0.19` / `0.20`).

Just adding something like this on a public module (perhaps `rend_types`?) would do the trick:

```rust
pub mod rend3_glam {
    pub use glam::*;
}
```

**Comment by jamen** [comment]
See also #178
