### ISSUE TITLE
DEVICE_LOST if `ready()` is called without submitting buffers

### ISSUE THREAD

**Issue by setzer22** [BVE-Reborn/rend3#295]
In some circumstances, calling `ready()` more than necessary seems to result in artifacts for loaded gltf models. I discovered this accidentally when I was calling `ready()` after loading a model. I did this to ensure all the queued actions on the renderer would get executed.

I am not sure whether the issue is with calling `ready()` twice in a row, or by doing it "too early". But I succesfully created this minimal reproducible example that shows the issue: https://github.com/setzer22/rend3-issue-repro-example

The example is mostly a copy from the `cube-no-framework` example. There's only two changes. A `load_model` function that loads a gltf model, and an extra call to `renderer.ready()` before the winit render loop is started. Commenting out that extra `renderer.ready()` call is enough to get the scene to render normally.

## Expected behavior
I added a cube, and this soldier gltf model, and they should display normally:
![image](https://user-images.githubusercontent.com/7241990/146566380-81ec7518-5dde-45fc-bdff-1dc270165e41.png)

## Actual behavior
Some parts of the soldier mesh disappear. And some others render incorrectly.
![image](https://user-images.githubusercontent.com/7241990/146566448-b1875a93-96b9-49be-80de-519d06ae29c0.png)

Here's a video showing the "incorrect rendering".
https://user-images.githubusercontent.com/7241990/146566595-14c11ad0-d1be-49fb-96e6-4305ff98fa92.mp4

**Comment by cwfitzgerald** [comment]
I found a potential issue here, the command buffers that ready returns are never submitted. If they get submitted, the model appears as they are supposed to.

That being said, this example causes DEVICE_LOST on my nvidia card, and  is likely invoking UB somewhere, which shouldn't be possible even if you don't submit that buffer.

**Comment by cwfitzgerald** [comment]
I'm closing this as stale, as a lot of things have happened.
