### ISSUE TITLE
Update egui version to 1.16.1 

### ISSUE THREAD

**Issue by resonant-jovian** [BVE-Reborn/rend3#312]
Egui recently got a new version, would be nice to use some new features, shouldn't be a huge change. (Version used is 0.15.0 and newest version is 0.16.1)

**Comment by cwfitzgerald** [comment]
There's an egui 0.16 branch up, was just waiting on the egui winit platform update to release. That's out, so I should be able to finish that today.

**Comment by resonant-jovian** [comment]
Great thanks.
