### ISSUE TITLE
Visual anomalies on macOS

### ISSUE THREAD

**Issue by TheNoswad** [BVE-Reborn/rend3#317]
When running on macOS Metal, there is a severe flickering of black stripes on meshes. This problem appears to have started after  #314 

### My specs
- macOS Catalina 10.15.7
- 1.6 GHz Dual-Core Intel Core i5
- Intel HD Graphics 6000 1536 MB

Attached is a video of the `scene-viewer` example exhibiting the issue.

https://user-images.githubusercontent.com/64293615/148565313-a68a3897-4678-42d6-af1a-ddc515803ffb.mov

**Comment by cwfitzgerald** [comment]
My guess is this is either a bug in wgpu/naga or a driver bug. It may also be mad at my negative shadow biases, but that would be super strange to me.

**Comment by cwfitzgerald** [comment]
Took a look at the generated MSL for the new shadow shader and nothing looks terribly amiss.

**Comment by cwfitzgerald** [comment]
This is fixed, just needs to be backported to wgpu 0.12. Marking as a blocker for release.

**Comment by cwfitzgerald** [comment]
Fix published in wgpu, closing.

**Comment by cwfitzgerald** [comment]
Unfortunately opening this back up, still happens on an M1

![image](https://user-images.githubusercontent.com/7861353/150684297-cfdeb48c-5d18-43d8-b3dc-356bb62b6001.png)

**Comment by cwfitzgerald** [comment]
Fix is in the works

**Comment by cwfitzgerald** [comment]
So this now works on MacOS 11+ and iOS 14+, need to follow up with bigger hammers for previous OSs.
