### ISSUE TITLE
Posssible mesh-damage bug.

### ISSUE THREAD

**Issue by John-Nagle** [BVE-Reborn/rend3#332]
This is caused by something I'm doing regarding order of operations, but I haven't found it yet.

Assets are being loaded, but by new code which may possibly be deleting a Mesh while it is in use. Or something.
The observed behavior is that meshes and textures are being loaded successfully, and then, suddenly, many meshes already loaded into the GPU have their triangle connections trashed. See the before and after pictures below. This happens all at once. 

This is repeatable.

Now, I'm doing a different order of mesh, material, and object loading than usual, so that's probably related. But it looks like something trashed the triangle vertex list, something I should not be able to do from safe code. Has this been seen before?

![rendertestbeforefail](https://user-images.githubusercontent.com/942608/150263496-4475dedb-f6dc-43d5-aa4a-7960209e2162.png)
![rendertestafterfail](https://user-images.githubusercontent.com/942608/150263532-54e65a99-5bc7-421c-9878-21b9dd5789d9.png)

**Comment by cwfitzgerald** [comment]
What version is this?

**Comment by John-Nagle** [comment]
0.2.2, the released version.
(corrected)

**Comment by cwfitzgerald** [comment]
0.2.3 has a patch which fixes an issue with meshes being improperly invalidated, so make sure you have the most recent patch. If it's still a problem with that version, I haven't seen that yet.

**Comment by John-Nagle** [comment]
Tried rend3 0.2.3, same results. 
(rend3-pbr is still 0.2.2; there is no 0.2.3 yet.)

I'm still not clear on what sets this off. It's not material loading; even with everything loaded as plain grey, it still happens. I'm probably replacing an existing object, but I haven't yet located the event which sets this off. When this happens varies from run to run.

**Comment by cwfitzgerald** [comment]
Interesting, definitely haven't seen this yet

**Comment by John-Nagle** [comment]
Working on narrowing it down. Looks like one specific object is causing a problem.

**Comment by John-Nagle** [comment]
Well, I can reproduce the problem consistently. I can load objects 0..597 with no trouble, and then on object #598, the displayed meshes all turn to junk as shown above. Always the same junk. I can dump object #598, and it has nothing special about it. I'm validating all the meshes (vertex count == normal count == uv count, tri count % 3 == 0, vertices in tri list in range, no dup vertices in a triangle), and all meshes validate OK.

If I quit loading just before object #598, the scene looks fine.
If I just skip object #598, instead of stopping, the problem occurs on some later object.
If I go back to an old version of my program, before I changed some of the order of events, it all works fine.
GPU memory usage is only 9% of 32GB at fail, so this is not an out of memory condition.

I need to look at this more. Any ideas?

**Comment by TheNoswad** [comment]
I can confirm that I have been having this issue as well.

**Comment by John-Nagle** [comment]
I think I see what might be happening.

![umbrellasgood](https://user-images.githubusercontent.com/942608/150400797-e0826f6c-3524-4e5d-ac86-8ce5d96a3e54.png)
![umbrellasbad](https://user-images.githubusercontent.com/942608/150400814-f1e0baa6-8a4d-49d7-bd5d-197f25700148.png)

See pictures above. The umbrellas are drawn correctly at first, and then suddenly the whole scene is garbled. Garbled in a very specific way. It looks like the vertices and UVs are fine, but the triangle indices were altered in a regular but wrong way. Such as being shifted by one, resulting in triangles formed by using vertices from adjacent triangles.

This suggests a bug in the memory management of vertex index arrays. As I understand it, it is customary at the Vulkan level to combine multiple objects into arrays. So arrays which grow have to be managed. That means resizing, growing, sometimes recopying when there's no room to grow in place, and possibly compacting after deletions. I would suggest looking for an off by one error in that memory management code. Thanks.

**Comment by cwfitzgerald** [comment]
I think I spotted one possible issue -- if a mesh gets deleted, and then the index buffer is resized at all, some objects may get pointed into the wrong indices. I'll try to give this a fix soon. Do you think this could be the problem?

**Comment by John-Nagle** [comment]
That sounds very likely. Some of my changes mean meshes are being deleted for the first time.

**Comment by cwfitzgerald** [comment]
Oops, didn't mean to close this, this _should_ be fixed on trunk, but going to hold this open until we validate it's fixed.

**Comment by John-Nagle** [comment]
OK. This problem has me stalled, because I was in the middle of a big code reorganization when I discovered it. Should I try to use the current trunk, or wait a bit? If I use trunk, there are major API changes not yet well documented, and I'm not sure if the API has stabilized yet, So I'd been waiting for a new crates.io version. But I have to have a fix for this to go forward. What do you suggest? A crates.io version that just has this mesh damage fix would be nice.

**Comment by cwfitzgerald** [comment]
I can try to backport this once I get word that it does indeed fix the problem. 0.3 is very close to release, but you shouldn't be forced to upgrade to get a bug fix like this, so I'm fine with backporting.

**Comment by John-Nagle** [comment]
Thanks. I'll have to convert to 0.3 eventually, so once that's out I will try to use it.

Right now, I've created a branch in my own code so I can work with the Github version, and am struggling with making that compile.

**Comment by John-Nagle** [comment]
Appears to be fixed in the version in the repository: https://github.com/BVE-Reborn/rend3.git#f2b7df4775919a0fc766e3a5718d8b4bba38bc28

I've converted over to that, so I don't need a backport. 

Here are the diffs to my code, to give a sense of what had to be changed to go from 0.2.3 to pre-0.3.x. This is useful only  as a guide to documentation, showing what had to be touched. I'm not using the 'framework".
[diffs.txt](https://github.com/BVE-Reborn/rend3/files/7962715/diffs.txt)

**Comment by cwfitzgerald** [comment]
Sounds good. 

Thank you for that diff, that is very helpful as I fill out the changelog.
