### ISSUE TITLE
Cube example won't run; no function with name 'floatBitsToUInt'

### ISSUE THREAD

**Issue by Rami-Slicer** [BVE-Reborn/rend3#335]
Starting the cube example causes the following error to appear before exiting:
```
[ERROR wgpu_hal::gles::egl] GLES: [ShaderCompiler/Error] ID 2 : 0:65(8): error: no function with name 'floatBitsToUInt'
```

**Comment by cwfitzgerald** [comment]
Thanks for the report, this an amusing typo upstream (the i in Uint should be lowercase). I'll try to file this with Naga tomorrow.
