### ISSUE TITLE
Shadow mapping issues when moving far away from the scene

### ISSUE THREAD

**Issue by setzer22** [BVE-Reborn/rend3#341]
See the attached video with the sample scene. When moving too far away everything starts to be covered in shadow. After some more distance, shadows disappear completely.

https://user-images.githubusercontent.com/7241990/151378367-cc5dbbd9-033a-452d-bc9c-9ce66cbf2e38.mp4

**Comment by cwfitzgerald** [comment]
Thanks for filing this, this is one of those issues I've just been ignoring/forgetting about, so good to have it on the issue tracker. Something about how I deal with the bounds of the shadow map is messed up.
