### ISSUE TITLE
Unclear how to set resolutoin after window resize in pre-0.3.x version

### ISSUE THREAD

**Issue by John-Nagle** [BVE-Reborn/rend3#344]
I've converted over to the unreleased 0.3.x version, to get past issue #332. That works. I'm not using the new "framework". Things are working well, except that window resize does not change the resolution. When I make the window full-screen from an initial small window, the large window has too low a resolution. 

Resizing code looks like this:

```
        Event::WindowEvent {
            event: WindowEvent::Resized(size),
            ..
        } => {
            //  Window resize
            let size = UVec2::new(size.width, size.height);
            // Reconfigure the surface for the new size.
            rend3::configure_surface(
                &surface,
                &renderer.device,
                format,
                size,
                rend3::types::PresentMode::Mailbox,
            );
            // Tell the renderer about the new aspect ratio.
            renderer.set_aspect_ratio(size.x as f32 / size.y as f32);
        }
```

It seems there should be a call to something to change the resolution, but there's no "renderer.set_resolution()" call available. Obviously I'm doing something wrong, but what?

**Comment by cwfitzgerald** [comment]
The missing part in that the render routine takes the resolution to render at as part of the arguments as we no longer need it retained.

See https://github.com/BVE-Reborn/rend3/blob/trunk/examples/cube-no-framework/src/main.rs#L200 and where resolution is modified in the resize method.

**Comment by John-Nagle** [comment]
Makes sense.
Should resolution be window size, or inner window size (minus frame)?

**Comment by cwfitzgerald** [comment]
Inner window size

**Comment by John-Nagle** [comment]
Thanks. I think some of the examples are using outer window size.

**Comment by cwfitzgerald** [comment]
The examples either use inner_size directly, or listen to the resize event which gives you the "client area" which is the same.
