### ISSUE TITLE
Unable to get shiny (metallic) material when not loading from GLTF.

### ISSUE THREAD

**Issue by John-Nagle** [BVE-Reborn/rend3#385]
Per discussion on Discord yesterday regarding materials not showing metallic-type reflection in Animats viewer.
Built a test case. This is based on the Rend3 example "cube-no-framework" and can be used as an example in Rend3's "examples" directory if added to the workspace list in the base Cargo.toml file. It draws a simple sphere and uses the same material parameters discussed on Discord yesterday. It's not showing any specular reflection at all. 

[sphere-no-framework.zip](https://github.com/BVE-Reborn/rend3/files/8386529/sphere-no-framework.zip)

**Comment by DerKarlos** [comment]
It works with 2 changes:
don't set: clearcoat_factor: Some(1.0),
roughness_factor: Some(0.4), // not good: 0.9 as I mentioned

**Comment by John-Nagle** [comment]
![metalliconclearcoatoff](https://user-images.githubusercontent.com/942608/161113942-4b3afba5-a551-46b8-a640-16c6eda91b32.png)

Yes. Turned off clearcoat factor and clearcoat roughness for above picture. Clearcoat factor alone overrides metallic. Thanks.

**Comment by John-Nagle** [comment]
This is simply that Rend3 doesn't do environmental reflections at all yet. Expected future feature, but not a bug.
