### ISSUE TITLE
Crash cross-compiled from Linux->Win64, running under Wine, full screen mode only.

### ISSUE THREAD

**Issue by John-Nagle** [BVE-Reborn/rend3#399]
Trying full screen mode on a cross-compiled Windows executable. Rend3 fails, unwrapping an error.

```
 wine ui-mock.exe
0104:fixme:system:EnableNonClientDpiScaling (000000000001004A): stub
0104:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0104:fixme:dxgi:dxgi_factory_EnumAdapterByGpuPreference Ignoring GPU preference 0x2.
0104:fixme:dxgi:dxgi_factory_EnumAdapterByGpuPreference Ignoring GPU preference 0x2.
0074:fixme:imm:ImeSetActiveContext (0x3a9e0, 0): stub
0074:fixme:imm:ImmReleaseContext (0000000000010020, 000000000003A9E0): stub
0104:fixme:imm:ImeSetActiveContext (0x77790, 1): stub
0104:fixme:imm:ImmReleaseContext (000000000001004A, 0000000000077790): stub
0104:fixme:explorerframe:taskbar_list_MarkFullscreenWindow iface 0000000000083450, hwnd 000000000001004A, fullscreen true stub!
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Outdated', /home/john/.cargo/git/checkouts/re
nd3-e03f89403de3386a/74d1e12/rend3/src/graph/graph.rs:304:62
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

The error in rend3's "graph.rs" is at

```
                // TODO: error
                // SAFETY: Same context as the above unsafe.
                unsafe { &mut *output_cell.get() }.acquire().unwrap();
```
It kind of looks like Rend3 is in the process of handling some kind of error.

This program will run correctly under Wine if full screen mode is not used.  

To turn off full screen mode, comment out line 90 in main.rs:

`window.set_fullscreen(Some(winit::window::Fullscreen::Borderless(None)));`

This program will run on Ubuntu 20.04 LTS in both full-screen and windowed modes. On simulated Windows, it will only run in windowed mode. I haven't tried real Windows, lacking a modern Windows machine.

Program is a mock user interface on Github: https://github.com/John-Nagle/ui-mock.git 793f019..c2a0c67

Compiled on Ubuntu 20.04 LTS with: cargo build --target x86_64-pc-windows-gnu

This program is a small mockup of the user interface for my metaverse client. I'm using it as a test case for the various target environments I need to support, because it's a much simpler program. It is bringing up Rend3 and egui, so it's a good way to test the interactions.

**Comment by John-Nagle** [comment]
Tried different backends:

Vulkan: Same crash.

DX12: Wine complains:

```
0104:fixme:d3dcompiler:D3DCompile2 HLSL shader compilation is not yet implemented.
[ERROR wgpu::backend::direct] Handling wgpu errors as fatal by def
ault
thread 'main' panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_compute_pipeline
      note: label = `BufferCopier Pipeline`
    Internal error: D3DCompile error (not implemented)
```

DX11:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: No supported adapter found', /home/john/.carg
o/git/checkouts/rend3-e03f89403de3386a/74d1e12/rend3-framework/src/lib.rs:205:38
stack backtrace:

```

So, no quick workaround that way.

**Comment by John-Nagle** [comment]
Created branch of mock-ui for test case. 
To get test case:

```
git clone https://github.com/John-Nagle/ui-mock.git
cd ui-mock
git checkout bug-windows-full-screen
```

This isn't urgent, but enough triage to determine whether it's a Rend3 bug, an Egui bug, a Winit bug, or a Wine bug would be helpful. Maybe the buck can be passed to another project.

**Comment by cwfitzgerald** [comment]
Ran it on my windows 10 machine and it works perfectly. Based on the log this is an issue of wine not properly supporting the apis to go fullscreen. That being said, we need to be handling outdated, as this still shouldn't crash. So tl;dr: partly rend3's problem partly wine's.

**Comment by John-Nagle** [comment]
That makes sense. I will file a bug report to Wine land.

Incidentally, it also crashes under Wine when you minimize the window.

I'm working through the problems of cross-platform GUI, building, and packaging with that "mock-ui" program. It's something others can easily build and run, so it's good for bug reports.

**Comment by John-Nagle** [comment]
Did you build natively on Windows 10? I've been cross-compiling. If so, could you please provide me with a copy of the executable? I want to try that under Wine. That will establish whether this is a cross-compile problem or a Wine problem.

**Comment by cwfitzgerald** [comment]
Yeah, this was natively compiled against the x86_64-windows-pc-msvc target. I uploaded the exe here: https://cdn.cwfitz.com/static/ui-mock.exe

**Comment by John-Nagle** [comment]
OK, tried that under Wine 7. Fails in exactly the same way:

```
0100:fixme:explorerframe:taskbar_list_MarkFullscreenWindow iface 00000000001A3CC0, hwnd 000000000001004A, fullscreen true stub!
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Outdated
', C:\Users\conno\.cargo\git\checkouts\rend3-e03f89403de3386a\74d1e12\rend3\src\
graph\graph.rs:304:62
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose bac
ktrace.

```
So it's Wine, not the cross-compiling process. I will file a Wine bug report.

**Comment by John-Nagle** [comment]
Reported as Wine bug: https://bugs.winehq.org/show_bug.cgi?id=53115

**Comment by John-Nagle** [comment]
Not a Rend3 bug.
