### ISSUE TITLE
Rend3 vs Tracy - versions

### ISSUE THREAD

**Issue by John-Nagle** [BVE-Reborn/rend3#403]
This is just for documentation.

Tracy, the profiling system, had some breaking changes after version 0.12. To make it work again with Rend3, here's what seems to be needed.

## The main program must start the Tracy client explicitly.

```
fn main() {
    #[cfg(feature = "tracy")]
    let _client = tracy_client::Client::start();    // enable profiler if "tracy" feature is on
   ...
```
In older versions of the Tracy client, just including the Tracy client turned on Tracy.
## Cargo.toml
```
[features]
#   Feature "tracy" enables profiling with Tracy
tracy = ["tracy-client", "profiling/profile-with-tracy"]

[dependencies]
tracy-client = {version = "0.13", optional = true }
profiling = { version = "1", default-features = false }
```
## Tracy-release (the profiler tool)
Use version 0.8.1. Older versions will not work.
## Build commands
Tracing enabled:
`cargo build --features tracy --release`
Tracing not enabled
`cargo build  --release`

**Comment by cwfitzgerald** [comment]
For future reference, https://github.com/nagisa/rust_tracy_client/tree/main/tracy-client is a table of tracy-client to tracy versions
