### ISSUE TITLE
Minimize window causes unwrap panic on Windows / Wine. OK on Linux

### ISSUE THREAD

**Issue by John-Nagle** [BVE-Reborn/rend3#408]
Minimized window under Wine while egui/rend3 running. Cross compiled from Linux with target x86_64-pc-windows-gnu

Rend3 is a simple static cube.
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Outdated',
/home/john/.cargo/git/checkouts/rend3-e03f89403de3386a/74d1e12/ren
d3/src/graph/graph.rs:304:62
stack backtrace:
```
Reproduce by:

```
git clone https://github.com/John-Nagle/ui-mock
cd ui-mock
cargo build --examples --release --target x86_64-pc-windows-gnu
cd target/x86_64-pc-windows-gnu/release/examples
wine ui-mock.exe
```
Minimize window using _ in top bar.

Trouble in graph.rs is at the `unwrap` below.

```
                // TODO: error
                // SAFETY: Same context as the above unsafe.
                unsafe { &mut *output_cell.get() }.acquire().unwrap();
```
So, known trouble spot. 

Part of my ongoing effort to resolve integration and portability issues for **egui/winit/rend3/rfd** in a simple program before integration into a big, harder to test system. Not high priority.

**Comment by cwfitzgerald** [comment]
This should have been long fixed - notably that this is now on the user to properly handle
