### ISSUE TITLE
Skeleton manager panics when removing a mesh with a skeleton

### ISSUE THREAD

**Issue by setzer22** [BVE-Reborn/rend3#421]
I'm currently investigating this issue where removing a skeleton mesh causes a panic with the following stacktrace:
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', rend3/src/managers/skeleton.rs:131:83
stack backtrace:
   (...)
   4: rend3::managers::skeleton::SkeletonManager::ready::{{closure}}
             at ./rend3/src/managers/skeleton.rs:131:25
   5: rend3::util::registry::basic::ResourceRegistry<T,HandleType>::remove_all_dead
             at ./rend3/src/util/registry/basic.rs:45:17
   6: rend3::managers::skeleton::SkeletonManager::ready
             at ./rend3/src/managers/skeleton.rs:126:9
   7: rend3::renderer::ready::ready
             at ./rend3/src/renderer/ready.rs:166:5
   8: rend3::renderer::Renderer::ready
             at ./rend3/src/renderer/mod.rs:557:9
   (...)
```

I've isolated this in the following reproduction example in my branch. Pressing Spacebar will remove one of the animated objects, which causes the cleanup code to run and the panic happens: https://github.com/BVE-Reborn/rend3/compare/trunk...Cakefish:rend3:skeleton_issue_repro

I don't think this used to be the case on previous versions, since I was orignally able to despawn meshes with skeleton just fine :thinking:  I'm going to try this same reproduction example on older versions to see if I can know when the bug was introduced (or maybe it's been there from the start?), but in the meantime: Is there anything that changed recently that would've made this code to fail?

```rust
        self.registry.remove_all_dead(|_, handle_idx, skeleton| {
            self.global_joint_count -= skeleton.joint_matrices.len();

            // Clean back references in the mesh data
            let mesh = mesh_manager.internal_data_mut(skeleton.mesh_handle.get_raw());
            let index = mesh.skeletons.iter().position(|sk| sk.idx == handle_idx).unwrap();  // <------- panic here
            mesh.skeletons.swap_remove(index);

            // Free the owned region of the vertex buffer
            mesh_manager.free_skeleton_mesh(skeleton.skeleton_vertex_range);
        });
```

**Comment by setzer22** [comment]
After investigating a bit more, it seems that the `handle_idx` that `remove_all_dead` gives me is `0`, but the skeleton index that was inserted on the mesh is `4` so the comparison `sk.idx == handle_idx` returns false.

**Comment by setzer22** [comment]
Actually, I don't think that `handle_idx` means what I think it means :thinking:. The `remove_all_dead` function is implemented here:
```rust
    pub fn remove_all_dead(&mut self, mut func: impl FnMut(&mut Self, usize, T)) {
        profiling::scope!("ResourceRegistry::remove_all_dead");
        for idx in (0..self.mapping.len()).rev() {
            let element = self.mapping.get_index(idx).unwrap().1;
            if element.refcount.strong_count() == 0 {
                let (_, value) = self.mapping.swap_remove_index(idx).unwrap();
                func(self, idx, value.data)
            }
        }
    }
```
The index here is just a value from `0` to `mapping.len()`, so apparently there is no correlation between the actual ids of the IndexMap (RawHandle) and the indices that are sent to the closure inside `remove_all_dead`. Is that the intended behavior? Right now I'm unsure how that index is meant to be used.

**Comment by cwfitzgerald** [comment]
That index is there so that, if you're maintaining parallel structures to the registry, you can do the same swap removal that the registry does so that your vector is laid out the same. How we're using it in the callback is wrong. This whole thing is a total mess and I'm looking at cleaning it up right now because everything is too tightly coupled.
