### ISSUE TITLE
Frustum culling and transform update seem to be in conflict.

### ISSUE THREAD

**Issue by John-Nagle** [BVE-Reborn/rend3#475]
Video:

https://video.hardlimit.com/w/23Rq8jeMgpaCVnxFkceMM4
(Transcoding in progress, may not be live yet)

What seems to be happening is that moving an object and rotating the camera can make an object disappear. Its shadow, however, does not disappear. Since there's no way to ask Rend3 to make an object disappear while keeping its shadow, this seems to be a culling bug.

Notes:
* This has been happening for some months; it's not been introduced by a recent version of Rend3.
* Moving and rotating the camera does not cause this problem for stationary objects.
* Moving objects while the camera remains stationary does not cause this problem.
* Video was made with Rend3 from commit 9eaa061001393a83402f1976ad3d22469c5369c6 on branch **fix-465**.

**Comment by John-Nagle** [comment]
Video https://video.hardlimit.com/w/23Rq8jeMgpaCVnxFkceMM4 is now live.

**Comment by John-Nagle** [comment]
Problem still exists at commit "4d10795" on branch main.

**Comment by cwfitzgerald** [comment]
Give `c2c2d32376ea4e3c77d5fbdbec385147f71c36ad` a try and see if that fixes it, the bounding sphere of the objects were never getting updated....

**Comment by John-Nagle** [comment]
It's working! Video:

https://video.hardlimit.com/w/bokNB3n9HiuxkUpq2BzwsS

**Comment by cwfitzgerald** [comment]
Nice! Will get that pr'd in
