### ISSUE TITLE
Damaged mesh - preliminary report

### ISSUE THREAD

**Issue by John-Nagle** [BVE-Reborn/rend3#480]
![Screenshot from 2023-03-25 21-50-07](https://user-images.githubusercontent.com/942608/227796210-5df995c7-1a78-483e-8b60-4d38e2cb926e.png)
![Screenshot from 2023-03-25 21-18-47](https://user-images.githubusercontent.com/942608/227796219-8aba6502-1d4c-4b59-a082-d6ec38b42e43.png)

New damaged mesh bug. This is preliminary. It might be my fault. I'm posting this in case it's been seen by someone else.

Notes:

- Intermittent. Appeared twice yesterday, on different executions of the program. Did not appear again,even in the same scene.
- In escalator image, both escalators are generated from the same MeshObject but with different textures. So the
mesh object is corrupted somehow.
- (The character on the right that's not fully assembled is normal. That's rigged mesh, without rigging implemented.)
- On a rerun, the same mesh object is not corrupted, so the file contents are OK.
- The mess of jaggy black triangles is supposed to be a two-sink bathroom vanity.
- That one had large jagged triangles sticking way outside the building.
- Some of those large jagged triangles disappeared as the viewpoint moved, suggesting a problem that happened after the culling sphere was computed.
- Seen with Rend3 rev = "c2c2d3237"
- Never seen in the past with Rend3 rev = "4d10795"  or earlier, although that scene has been looked at for the past year.

**Comment by John-Nagle** [comment]
Happened again. Still not repeatable.
![Screenshot from 2023-03-26 19-29-23](https://user-images.githubusercontent.com/942608/227829998-8d9e679e-1978-48aa-9abb-e369bb4cdf74.png)
![Screenshot from 2023-03-26 19-28-23](https://user-images.githubusercontent.com/942608/227830000-51c66f71-f234-4f74-b236-1ba9a583e7e3.png)

Only one Mesh in the Rend3 sense is corrupted,

**Comment by John-Nagle** [comment]
Progress! Got another failure. A picnic table is turning into a garbage mesh, much larger than the object is supposed to be. But frustum culling occurs based on the normal bounding volume of the garbaged object (a picnic table).

First. here's what the picnic table is supposed to look like, from a separate execution of the program.
![Screenshot from 2023-03-27 20-02-09](https://user-images.githubusercontent.com/942608/228117455-dc005f06-68ec-46ea-b8fd-fa6a3e7fc3d8.png)

Now, here are some views of the damaged mesh, from slightly different viewpoints. 
![Screenshot from 2023-03-27 19-57-39](https://user-images.githubusercontent.com/942608/228117811-6e7d2ebb-ebfe-4652-a382-7b82b1aa829e.png)
Here's the damaged mesh. Note the bag of chips, which sits atop the picnic table, or where the picnic table was supposed to appear. So the picnic table is within the viewing frustum here.

![Screenshot from 2023-03-27 19-57-43](https://user-images.githubusercontent.com/942608/228118093-f9f3fb4c-fc0d-4626-998c-a55132ab6cd4.png)
Here's a slightly different camera angle. The picnic table is outside the viewing frustum, and the damaged mesh disappears.

I've tried this from many different viewpoints and directions, and it's consistent. If the real object is outside the viewing frustum, the damaged mesh does not appear. If it's inside the viewing frustrum, it does. Lots more screenshots available.

So the mesh corruption is happening _after_ the bounding sphere is computed. That should narrow down the problem.

**Comment by John-Nagle** [comment]
![Screenshot from 2023-03-27 19-55-54](https://user-images.githubusercontent.com/942608/228118710-c5f666ad-17a0-4718-a30a-e964d21fd7b5.png)
Damaged mesh, from further away. Note that the viewing frustum, at its left edge, reaches the picnic table area in the background.

![Screenshot from 2023-03-27 19-55-52](https://user-images.githubusercontent.com/942608/228118910-de2f837b-db99-4170-a4d1-87b0b01d93e2.png)
A very slight turn of the camera, just enough to put the picnic table location outside the viewing frustum, and the damaged mesh is gone.

Distance doesn't matter. Direction of view doesn't matter. Only whether or not the damaged object is inside the viewing frustum seems to matter.

**Comment by John-Nagle** [comment]
So far, I have not seen this problem in GPU culling Rend3. But it was rare, so I can't be sure.

The other big visual defect, occasional single frames of all white, seems to have disappeared. So far, so good. More info to follow.

**Comment by cwfitzgerald** [comment]
I'm going to close this for now, if it re-appears, please let me know and I'll re-open.

**Comment by John-Nagle** [comment]
Agree. I have not seen that problem at all post GPU-culling.

**Comment by John-Nagle** [comment]
Sometimes, they come back.

![garbagegeom4](https://github.com/BVE-Reborn/rend3/assets/942608/f48ecdee-f1bd-4518-a4d2-f142b1b13b3b)
![garbagegeom3](https://github.com/BVE-Reborn/rend3/assets/942608/480b640f-78b7-412e-ae3a-6da440a85080)

This is intermittent. These misplaced triangles appear and disappear as the viewpoint changes. They do not move. They do not cast shadows. Hard to reproduce.

This test case is in a relatively simple scene which is nowhere near to filling up the GPU or hitting the 2GB limit.

Rend3 rev = "9065f1e", which is post GPU culling.

**Comment by cwfitzgerald** [comment]
There were some pretty major issues fixed in #551, but as always, if it's still there, please lmk and I'll re-open.

**Comment by John-Nagle** [comment]
Back again in rev c7c2d85.

**Comment by John-Nagle** [comment]
![junkrendering](https://github.com/BVE-Reborn/rend3/assets/942608/5fb5fb2e-f340-4cfa-9747-dbc19a2d5598)

Those lines across the sky are misplaced vertices. Moves in the viewpoint make them disappear or reapppear.
