### ISSUE TITLE
MeshManager::remove subscript error

### ISSUE THREAD

**Issue by John-Nagle** [BVE-Reborn/rend3#485]
![crashtryingnonblend](https://github.com/BVE-Reborn/rend3/assets/942608/0dda924a-a47e-4b88-9cca-38247d9e1f26)

Not repeatable. Only happened once.

Rend3 version: rev = "c2c2d3237". This is months old, but there's no official release version later than that.

Since Rend3 allocation will probably have change when [WGPU arcanization](https://github.com/gfx-rs/wgpu/pull/3626) is finished, this probably isn't worth much attention right now.

**Comment by cwfitzgerald** [comment]
Going to close for now, if it happens again, please re-open.
