### ISSUE TITLE
Fails on Linux/Wayland

### ISSUE THREAD

**Issue by John-Nagle** [BVE-Reborn/rend3#486]
./sharpview: symbol lookup error: /lib/x86_64-linux-gnu/libnvidia-vulkan-producer.so: undefined symbol: wlEglCreateSurfaceExport

Ubuntu 22.04.2 LTS, latest update. First time trying Wayland. Works with Xorg.

Will try other drivers.

**Comment by cwfitzgerald** [comment]
Seems to be an outdated library problem: https://github.com/NVIDIA/egl-wayland/issues/80

**Comment by John-Nagle** [comment]
Upgraded NVidia driver from 425 to 430. Segmentation fault running "cube".

Reproduced under gdb. 

 0x0000555556305eab in wgpu_hal::vulkan::Device::create_swapchain (self=0x5555577c4a50, surface=0x555557164f00, config=0x7fffffffa890, provided_old_swapchain=...)
    at src/vulkan/device.rs:606

Unclear whether WGPU or what is at fault.

Backtrace: 

[cubecrash.txt](https://github.com/BVE-Reborn/rend3/files/11911323/cubecrash.txt)

**Comment by cwfitzgerald** [comment]
I would guess it's a driver problem as it's crashing deep in the driver trying to dl_close something, might be worth trying vkcube?

**Comment by John-Nagle** [comment]
That's what I thought, too. It's some problem involving Linux, Wayland, Vulkan, and too many NVidia driver versions. Wayland vs. Nvidia is known to be ... difficult. But it's good to have it logged as a Rend3 issue, so that when it blows up for someone else, it's known.
