### ISSUE TITLE
Large meshes are sometimes only partially uploaded

### ISSUE THREAD

**Issue by OptimisticPeach** [BVE-Reborn/rend3#506]
When my mesh has a very large number of vertices, it will sometimes only be partially uploaded (or not uploaded at all).

A slimmed-down repro should be available at https://github.com/OptimisticPeach/rend3_repro -- it should be cloned into the same folder as a copy of `rend3` because it asks for a relative path `../rend3/<crate>`.

I did the most basic just trimming out unrelated things, but if it's still too cluttered let me know, and I can remove the terrain generation and instead make it just plain sphere generation. Anyway, if you launch the app (at least on my pc), you get a blank world, you need to press "reset world" a few times which regenerates the mesh each time you press it and reuploads it to rend3. If you go into `noise > subdivisions` in the egui window, you can change the subdivisions to trigger it again, the mesh is updated live as you change the subdivisions.

If you have any questions, please let me know.

The commit of rend3 used is `131396009adef94df17cc2eccf0571d46e07aed5`.

**Comment by marstaik** [comment]
I ran into this same issue on my end, and I can reproduce it with the reproduction above. You will need to clone `buttery` as well.
