### ISSUE TITLE
OOM In Render-Bench

### ISSUE THREAD

**Issue by John-Nagle** [BVE-Reborn/rend3#558]
![destroyedbyrend3](https://github.com/BVE-Reborn/rend3/assets/942608/2945d4be-40cd-467b-b2a3-aa8697b99c1a)

Tried new Rend3.

Cube test worked.

Rebuilt "render-bench" with new Rend3. 

Converted code where necessary for new Winit and new Rend3-Framework, but no other changes.

Rand "render-bench".

Try #1: Skybox was drawn, but hung at "Drawing permanent buildings". Exited OK.
Try #2: Segmentation fault.
Try #3: Running under GDB. Many threads seen to exit. GDB hung. Window manager hung. System completely unresponsive to keyboard and mouse. Continuous disk I/O in progress. After several minutes, finally had to press RESET. 

System failed to restart. See screenshot.

**This is very bad.** Is there hostile code in this build?

Ubuntu 22.04 LTS, unmodified.

**Comment by John-Nagle** [comment]
Recovery underway. File journal recovery reported about 50 lost files. Evaluating damage.

**Comment by John-Nagle** [comment]
So far, it looks like nothing important was lost. Whew.

This is very strange. render-bench doesn't write anything to disk. It just reads some images at startup. How could it possibly go into frantic disk activity for several minutes? That machine has 32GB of RAM and a small swap file only because Ubuntu creates one. No idea what it was doing.

I don't dare run it again. It's scary that it does more damage when run under gdb.

**Comment by cwfitzgerald** [comment]
Closing as this was due to OOM after request_redraw wasn't called in the main loop.
