### ISSUE TITLE
Relicense to MIT/Apache-2.0/Zlib

### ISSUE THREAD

**Issue by cwfitzgerald** [BVE-Reborn/rend3#58]
@cedric-h @Noxime Due to some concerns brought to my attention I want to relicense the lib to a triple license MIT/Apache-2.0/Zlib. As you are the other contributors, I need your sign off, could you just copy the following:

> I give permission for my contributions to the rend3 repository to be relicensed from MPL-2.0 to MIT/Apache-2.0/Zlib.

Cheers.

**Comment by Noxime** [comment]
Sounds good to me!

I give permission for my contributions to the rend3 repository to be relicensed from MPL-2.0 to MIT/Apache-2.0/Zlib.

**Comment by cedric-h** [comment]
I give permission for my contributions to the rend3 repository to be relicensed from MPL-2.0 to MIT/Apache-2.0/Zlib.

**Comment by cwfitzgerald** [comment]
Thank you both, closed in a40c9bdf93eeff8a8f725ce54c0eea373c836fba
