### ISSUE TITLE
Fields of LoadedGltfScene should be public

### ISSUE THREAD

**Issue by John-Nagle** [BVE-Reborn/rend3#64]
When a scene is loaded, the loader returns a LoadedGltfScene to the caller, with useful info such as all the material handles. But the fields of LoadedGltfScene are all private, so the caller can't use the result. 

Per email message, this was just an error, and those fields should be public. This is just to track that. Thanks.

**Comment by cwfitzgerald** [comment]
Fixed by 0f9ab05257d5e04c2b5bdd54769a9a037f48cdd1
