### ISSUE TITLE
GLTF loader - winding order reversed?

### ISSUE THREAD

**Issue by John-Nagle** [BVE-Reborn/rend3#71]
I'm uploading a simple cube created with Blender in GLTF format. Upload works fine, including textures, but objects appear inside out, probably because the winding order is reversed.  I know about flip_winding_order. But I can't use it when all I have is a mesh handle after the upload. I think it's too late by then.  

So here's a unit cube created in Blender, with normals pointing out, back faces being culled, and rendering properly in Blender. Something needs to be flipped, but I'm not sure what. 

[unitcube.zip](https://github.com/BVE-Reborn/rend3/files/5810600/unitcube.zip)

**Comment by cwfitzgerald** [comment]
When I view this mesh in scene viewer, everything works and expected. 

![image](https://user-images.githubusercontent.com/7861353/104514678-a3ca7100-55bf-11eb-9aa3-438c693efd97.png)

Are you modifying the transform of the cube at all? If you are, you need to keep in mind the gltf transform hirearchy, most importantly starting with a [transform that inverts the z axis and fixes the winding order](https://github.com/BVE-Reborn/rend3/blob/trunk/rend3-gltf/src/lib.rs#L92) (and coordinate system).

**Comment by cwfitzgerald** [comment]
Closing as not an issue per email.
