### ISSUE TITLE
Illegal instruction crash if GPU memory fills during texture loading

### ISSUE THREAD

**Issue by John-Nagle** [BVE-Reborn/rend3#89]
Loaded more textures than will fit in a 2GB NVidia 640. This was detected by WGPU but the shutdown process caused an illegal instruction. 

========

Loaded 11025 meshes, 520701 vertices, 775664 triangles, 0 materials. Duplicate meshes: 95640. duplicate materials: 103597)
basisu_transcoder::basisu_transcoder_init: Initializing (this is not an error)
wgpu error: Validation Error

Caused by:
    In Device::create_texture
    not enough memory left

thread '<unnamed>' panicked at 'Handling wgpu errors as fatal by default', /home/john/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.7.0/src/backend/direct.rs:1896:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'Job panicked!', /home/john/.cargo/registry/src/github.com-1ecc6299db9ec823/switchyard-0.1.1/src/lib.rs:153:78
[1459.618951 ERROR]()(gpu_descriptor::allocator): `DescriptorAllocator` is dropped while some descriptor sets were not deallocated
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `63`,
 right: `0`: Allocator dropped before all sets were deallocated', /home/john/.cargo/registry/src/github.com-1ecc6299db9ec823/gpu-descriptor-0.1.0/src/allocator.rs:117:9
stack backtrace:
   0:     0x55f50c9b68f0 - std::backtrace_rs::backtrace::libunwind::trace::h72c2fb8038f1bbee
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
   1:     0x55f50c9b68f0 - std::backtrace_rs::backtrace::trace_unsynchronized::h1e3b084883f1e78c
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/mod.rs:66
   2:     0x55f50c9b68f0 - std::sys_common::backtrace::_print_fmt::h3bf6a7ebf7f0394a
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:79
   3:     0x55f50c9b68f0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2e8cb764b7fe02e7
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:58
   4:     0x55f50c9d9a4c - core::fmt::write::h7a1184eaee6a8644
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/fmt/mod.rs:1080
   5:     0x55f50c9af122 - std::io::Write::write_fmt::haeeb374d93a67eac
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/io/mod.rs:1516
   6:     0x55f50c9b8dbd - std::sys_common::backtrace::_print::h1d14a7f6ad632dc8
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:61
   7:     0x55f50c9b8dbd - std::sys_common::backtrace::print::h301abac8bb2e3e81
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:48
   8:     0x55f50c9b8dbd - std::panicking::default_hook::{{closure}}::hde0cb80358a6920a
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:208
   9:     0x55f50c9b8a68 - std::panicking::default_hook::h9b1a691049a0ec8f
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:227
  10:     0x55f50c9b94a1 - std::panicking::rust_panic_with_hook::h2bdec87b60580584
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:577
  11:     0x55f50c9b9049 - std::panicking::begin_panic_handler::{{closure}}::h101ca09d9df5db47
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:484
  12:     0x55f50c9b6d5c - std::sys_common::backtrace::__rust_end_short_backtrace::h3bb85654c20113ca
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:153
  13:     0x55f50c9b9009 - rust_begin_unwind
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
  14:     0x55f50c9b8fbb - std::panicking::begin_panic_fmt::hf0503558fbe5b251
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:437
  15:     0x55f50b745c2d - <gpu_descriptor::allocator::DescriptorBucket<P> as core::ops::drop::Drop>::drop::h5e4a19ead60be931
                               at /home/john/.cargo/registry/src/github.com-1ecc6299db9ec823/gpu-descriptor-0.1.0/src/allocator.rs:117
  16:     0x55f50b785c86 - core::ptr::drop_in_place::h5828905358069ef8
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ptr/mod.rs:175
  17:     0x55f50b7848a6 - core::ptr::drop_in_place::h4bda2bbdbd47fec9
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ptr/mod.rs:175
  18:     0x55f50b50784b - core::ptr::mut_ptr::<impl *mut T>::drop_in_place::he86a3cddf5a4d6a5
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ptr/mut_ptr.rs:963
  19:     0x55f50b5b885f - hashbrown::raw::inner::Bucket<T>::drop::ha47d523b956a0163
                               at /home/john/.cargo/registry/src/github.com-1ecc6299db9ec823/hashbrown-0.9.1/src/raw/mod.rs:334
  20:     0x55f50b5b4866 - <hashbrown::raw::inner::RawTable<T> as core::ops::drop::Drop>::drop::h105ee02b6ea7cf65
                               at /home/john/.cargo/registry/src/github.com-1ecc6299db9ec823/hashbrown-0.9.1/src/raw/mod.rs:1387
  21:     0x55f50b7840cf - core::ptr::drop_in_place::h4786921e285cbfc4
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ptr/mod.rs:175
  22:     0x55f50b77c6e6 - core::ptr::drop_in_place::h0213673b67baf8c1
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ptr/mod.rs:175
  23:     0x55f50b78fe5a - core::ptr::drop_in_place::hacf55534fef6e1aa
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ptr/mod.rs:175
  24:     0x55f50b77f10f - core::ptr::drop_in_place::h1b46548e8012edf3
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ptr/mod.rs:175
  25:     0x55f50b791fef - core::ptr::drop_in_place::hbe8c27a9edba9352
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ptr/mod.rs:175
  26:     0x55f50b78ecd6 - core::ptr::drop_in_place::h9f77aeb4d1100c4b
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ptr/mod.rs:175
  27:     0x55f50b788836 - core::ptr::drop_in_place::h6f664697b36b8dee
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ptr/mod.rs:175
  28:     0x55f50b788b64 - core::ptr::drop_in_place::h70843b84556dce5c
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ptr/mod.rs:175
  29:     0x55f50b78b8b1 - core::ptr::drop_in_place::h86922aefa0a8ed15
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ptr/mod.rs:175
  30:     0x55f50b662695 - <alloc::vec::Vec<T> as core::ops::drop::Drop>::drop::h7542706d30e0345a
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/alloc/src/vec.rs:2636
  31:     0x55f50b780a86 - core::ptr::drop_in_place::h270d3a1f4531a1f6
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ptr/mod.rs:175
  32:     0x55f50b77d93f - core::ptr::drop_in_place::h0d2464cd9aa97aca
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ptr/mod.rs:175
  33:     0x55f50b78f18f - core::ptr::drop_in_place::ha1a0f77630897ed5
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ptr/mod.rs:175
  34:     0x55f50b7967a6 - core::ptr::drop_in_place::he13d6f40fd569a65
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ptr/mod.rs:175
  35:     0x55f50b7810e1 - core::ptr::drop_in_place::h2a2a04648e904b36
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ptr/mod.rs:175
  36:     0x55f50b78b00b - core::ptr::drop_in_place::h83ea081e6953d0c0
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ptr/mod.rs:175
  37:     0x55f50b784176 - core::ptr::drop_in_place::h47ac94a81d232930
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ptr/mod.rs:175
  38:     0x55f50b78a5c5 - core::ptr::drop_in_place::h7e3cd6914d149c5f
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ptr/mod.rs:175
  39:     0x55f50b793995 - core::ptr::drop_in_place::hcb1f637cd1356135
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ptr/mod.rs:175
  40:     0x55f50b6aa294 - alloc::sync::Arc<T>::drop_slow::h201315f20f1d779c
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/alloc/src/sync.rs:934
  41:     0x55f50b6acf96 - <alloc::sync::Arc<T> as core::ops::drop::Drop>::drop::h6ca7779db10891ba
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/alloc/src/sync.rs:1454
  42:     0x55f50b78a25f - core::ptr::drop_in_place::h7d7724a6ca05d6a8
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ptr/mod.rs:175
  43:     0x55f50a5561b5 - core::ptr::drop_in_place::h149b562205c5bed4
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ptr/mod.rs:175
  44:     0x55f50a5675ef - core::ptr::drop_in_place::hfc18b9422961468c
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ptr/mod.rs:175
  45:     0x55f50a55cf85 - core::ptr::drop_in_place::h7809123838c49547
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ptr/mod.rs:175
  46:     0x55f50a55932e - core::ptr::drop_in_place::h366826405ae70a82
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ptr/mod.rs:175
  47:     0x55f50a555c1e - core::ptr::drop_in_place::h10608e5e86d50673
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ptr/mod.rs:175
  48:     0x55f50a66f7e2 - alloc::sync::Arc<T>::drop_slow::h32b75a7197f4384e
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/alloc/src/sync.rs:934
  49:     0x55f50a56a324 - <alloc::sync::Arc<T> as core::ops::drop::Drop>::drop::hd89e180652d5182f
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/alloc/src/sync.rs:1454
  50:     0x55f50a5608be - core::ptr::drop_in_place::ha17f0dacadc87931
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ptr/mod.rs:175
  51:     0x55f50a5672ed - core::ptr::drop_in_place::hfa9e84442f022b56
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ptr/mod.rs:175
  52:     0x55f50a50a679 - winit::platform_impl::platform::x11::EventLoop<T>::run_return::hea8200ffd372b259
                               at /home/john/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/linux/x11/mod.rs:392
  53:     0x55f50a50bb1b - winit::platform_impl::platform::x11::EventLoop<T>::run::h727d6fdff40e6337
                               at /home/john/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/linux/x11/mod.rs:398
  54:     0x55f50a4ce0de - winit::platform_impl::platform::EventLoop<T>::run::h13ae2d1f1e555cb3
                               at /home/john/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/linux/mod.rs:652
  55:     0x55f50a57b854 - winit::event_loop::EventLoop<T>::run::h89dd547d9cc80018
                               at /home/john/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/event_loop.rs:154
  56:     0x55f50a65bc21 - slscenetester::displaystate::h2be6aceb304627d8
                               at /home/john/projects/sl/SL-test-viewer/slscenetester/src/main.rs:342
  57:     0x55f50a65d146 - slscenetester::main::h8e6f02da263145b5
                               at /home/john/projects/sl/SL-test-viewer/slscenetester/src/main.rs:616
  58:     0x55f50a5535eb - core::ops::function::FnOnce::call_once::h17c7a85cc44fd5c7
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ops/function.rs:227
  59:     0x55f50a47c77e - std::sys_common::backtrace::__rust_begin_short_backtrace::h419441424f556d8b
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:137
  60:     0x55f50a579781 - std::rt::lang_start::{{closure}}::hc8f76a53b20d1856
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/rt.rs:66
  61:     0x55f50c9b99b7 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::he179d32a5d10d957
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ops/function.rs:259
  62:     0x55f50c9b99b7 - std::panicking::try::do_call::hcb3d5e7be089b2b4
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:381
  63:     0x55f50c9b99b7 - std::panicking::try::h7ac93b0cd56fb701
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:345
  64:     0x55f50c9b99b7 - std::panic::catch_unwind::h7b40e396c93a4fcd
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panic.rs:382
  65:     0x55f50c9b99b7 - std::rt::lang_start_internal::h142b9cc66267fea1
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/rt.rs:51
  66:     0x55f50a579757 - std::rt::lang_start::h8665b9cdee759f71
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/rt.rs:65
  67:     0x55f50a65d19a - main
  68:     0x7fe2654cabf7 - __libc_start_main
  69:     0x55f50a47b32a - _start
  70:                0x0 - <unknown>
thread panicked while panicking. aborting.
Illegal instruction (core dumped)

**Comment by cwfitzgerald** [comment]
Going to close this for now as there have been a complete rewrite of the backends since this problem.
